name: Continuous Integration - Dice Parser

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make Project
      run: gcc main.c parser.c -o dice 
    - name: Release Project
      uses: actions/upload-artifact@v4
      with:
        name: Dice Parser
        path: ./dice
