name: Continuous Integration - Dice Parser

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Make Dice Parser
      run: make 
    - name: Make Histogram Tool
      run: make histogram
    - name: Make Unit Testing Tool
      run: make unittests
    - name: Run Unit Tests
      run: ./unittests >> test_results.txt
    - name: Release Project
      uses: actions/upload-artifact@v4
      with:
        name: Dice Parser Deliverables
        path: ./dice ./histogram ./test_results.txt
